export * from './answer.model';
export * from './question.model';
export * from './agent.model';
export * from './alert';
export * from './business.model';
export * from './cardschema';
export * from './cardstore';
export * from './carrier.model';
export * from './client.model';
export * from './company.model';
export * from './condition.model';
export * from './coverage.model';
export * from './cta.model';
export * from './discount.model';
export * from './driver.model';
export * from './dynamic-coverage-spec.model';
export * from './dynamic-coverage.model';
export * from './dynamic-rate-condition.model';
export * from './dynamic-rater.model';
export * from './email.model';
export * from './form.model';
export * from './home.model';
export * from './incident.model';
export * from './landing-page.model';
export * from './lifecycle-analytic.model';
export * from './lifecycle.model';
export * from './location.model';
export * from './medium.model';
export * from './page.model';
export * from './user.model';
export * from './recreational-vehicle.model';
export * from './rater.model';
export * from './rate.model';
export * from './parameter.model';
export * from './vehicle.model';
export * from './service-responses.models';
export * from './summary.model';
export * from './form-completed-page.model';

export interface Theme {
  'brand-color': string;
  'brand-color-light': string;
  'hover-color': string;
  'secondary-color': string;
  'secondary-color-light': string;
}
