import { returnArrayByKey } from './ez-arrays';

export const fields = [
    { type: 'Applicant', keys: [
        {key: 'FirstName', label: 'First Name', xiloKey: 'firstName', xiloObject: 'client', fieldType: 'text', required: true},
        {key: 'LastName', label: 'Last Name', xiloKey: 'lastName', xiloObject: 'client', fieldType: 'text', required: true},
        {key: 'DOB', label: 'DOB', xiloKey: 'birthDate', xiloObject: 'client', fieldType: 'date', startDate: '01/01/1990'},
        {key: 'SSN', label: 'SSN', xiloKey: 'ssn', xiloObject: 'client', fieldType: 'password'},
        {key: 'Gender', label: 'Gender', xiloKey: 'gender', xiloObject: 'client', fieldType: 'select'},
        {key: 'MaritalStatus', label: 'Marital Status', xiloKey: 'maritalStatus', xiloObject: 'client', fieldType: 'select'},
        {key: 'Industry', label: 'Industry', xiloKey: 'industry', xiloObject: 'client', fieldType: 'industry'},
        {key: 'Occupation', label: 'Occupation', xiloKey: 'occupation', xiloObject: 'client', fieldType: 'occupation'},
        {key: 'Education', label: 'Education', xiloKey: 'educationLevel', xiloObject: 'client', fieldType: 'select'},
        {key: 'Relation', label: 'Relation', xiloKey: 'relationship', xiloObject: 'client', fieldType: 'select'},
        {key: 'Email', label: 'Email', xiloKey: 'email', xiloObject: 'client', fieldType: 'email'},
        {key: 'PhoneNumber', label: 'Phone', xiloKey: 'phone', xiloObject: 'client', fieldType: 'number'},
    ]},
    { type: 'CoApplicant', keys: [
        {key: 'FirstName', label: 'First Name', xiloKey: 'spouseFirstName', xiloObject: 'client', fieldType: 'text', required: true },
        {key: 'LastName', label: 'Last Name', xiloKey: 'spouseLastName', xiloObject: 'client', fieldType: 'text', required: true },
        {key: 'DOB', label: 'DOB', xiloKey: 'spouseBirthdate', xiloObject: 'client', fieldType: 'date', startDate: '01/01/1993' },
        {key: 'SSN', label: 'SSN', xiloKey: 'spouseSsn', xiloObject: 'client', fieldType: 'password' },
        {key: 'Gender', label: 'Gender', xiloKey: 'spouseGender', xiloObject: 'client', fieldType: 'select', options: returnArrayByKey('gender')},
        {key: 'MaritalStatus', label: 'Marital Status', xiloKey: 'spouseMaritalStatus', xiloObject: 'client', fieldType: 'select', options: returnArrayByKey('maritalStatus')},
        {key: 'Industry', label: 'Industry', xiloKey: 'spouseIndustry', xiloObject: 'client', fieldType: 'industry' },
        {key: 'Occupation', label: 'Occupation', xiloKey: 'spouseOccupation', xiloObject: 'client', fieldType: 'occupation' },
        {key: 'Education', label: 'Education', xiloKey: 'spouseEducationLevel', xiloObject: 'client', fieldType: 'select', options: returnArrayByKey('educationLevel') },
        {key: 'Relation', label: 'Relation', xiloKey: 'spouseRelationship', xiloObject: 'client', fieldType: 'select', options: returnArrayByKey('relationship') },
        {key: 'Email', label: 'Email', xiloKey: 'spousePhoneNumber', xiloObject: 'client', fieldType: 'number'},
        {key: 'PhoneNumber', label: 'Phone', xiloKey: 'spouseEmail', xiloObject: 'client', fieldType: 'email'},
    ]},
    { type: 'Home', keys: [
        { key: 'FullAddress', label: 'Full Address', xiloKey: 'fullAddress', xiloObject: 'homes', fieldType: 'text', events: ['isAddressSearch', 'getHomeData'] },
        { key: 'StreetName', label: 'Home Street Name', xiloKey: 'streetName', xiloObject: 'homes', fieldType: 'text' },
        { key: 'StreetNumber', label: 'Home Street Number', xiloKey: 'streetNumber', xiloObject: 'homes', fieldType: 'text' },
        { key: 'UnitNumber', label: 'Home Unit Number', xiloKey: 'unitNumber', xiloObject: 'homes', fieldType: 'text' },
        { key: 'City', label: 'Home City', xiloKey: 'city', xiloObject: 'homes', fieldType: 'text' },
        { key: 'StateCode', label: 'Home State Code', xiloKey: 'state', xiloObject: 'homes', fieldType: 'text' },
        { key: 'County', label: 'Home County', xiloKey: 'county', xiloObject: 'homes', fieldType: 'text' },
        { key: 'Zip5', label: 'Home Zip5', xiloKey: 'zipCode', xiloObject: 'homes', fieldType: 'number' },
        { key: 'YearsAtAddress', label: 'Years At Address', xiloKey: 'yearsAtAddress', xiloObject: 'homes', fieldType: 'select'},
    ]},
    { type: 'Address', keys: [
        { key: 'FullAddress', label: 'Full Address', xiloKey: 'fullAddress', xiloObject: 'client', fieldType: 'text', events: ['isAddressSearch'] },
        { key: 'AddressCode', label: 'Address Code', xiloKey: 'addressCode', xiloObject: 'client', fieldType: 'select'},
        { key: 'StreetName', label: 'Address Street Name', xiloKey: 'streetName', xiloObject: 'client', fieldType: 'text' },
        { key: 'StreetNumber', label: 'Address Street Number', xiloKey: 'streetNumber', xiloObject: 'client', fieldType: 'text' },
        { key: 'UnitNumber', label: 'Address Unit Number', xiloKey: 'unitNumber', xiloObject: 'client', fieldType: 'text' },
        { key: 'City', label: 'Address City', xiloKey: 'city', xiloObject: 'client', fieldType: 'text' },
        { key: 'StateCode', label: 'Address State Code', xiloKey: 'stateCd', xiloObject: 'client', fieldType: 'select', options: returnArrayByKey('state') },
        { key: 'County', label: 'Address County', xiloKey: 'county', xiloObject: 'client', fieldType: 'text' },
        { key: 'Zip5', label: 'Address Zip5', xiloKey: 'postalCd', xiloObject: 'client', fieldType: 'number' },
        { key: 'YearsAtAddress', label: 'Years At Address', xiloKey: 'yearsAtCurrentAddress', xiloObject: 'client', fieldType: 'select'}
    ]},
    { type: 'AltDwelling', keys: [
        { key: 'AddressCode', label: 'Address Code', xiloKey: 'addressCode', xiloObject: 'homes', fieldType: 'select'},
        { key: 'FullAddress', label: 'Full Address', xiloKey: 'fullAddress', xiloObject: 'homes', fieldType: 'text', events: ['isAddressSearch']  },
        { key: 'StreetName', label: 'Dwelling Street Name', xiloKey: 'streetName', xiloObject: 'homes', fieldType: 'text' },
        { key: 'StreetNumber', label: 'Dwelling Street Number', xiloKey: 'streetNumber', xiloObject: 'homes', fieldType: 'text' },
        { key: 'UnitNumber', label: 'Dwelling Unit Number', xiloKey: 'unitNumber', xiloObject: 'homes', fieldType: 'text' },
        { key: 'City', label: 'Dwelling City', xiloKey: 'city', xiloObject: 'homes', fieldType: 'text' },
        { key: 'StateCode', label: 'Dwelling State Code', xiloKey: 'state', xiloObject: 'homes', fieldType: 'select', options: returnArrayByKey('state') },
        { key: 'County', label: 'Dwelling County', xiloKey: 'county', xiloObject: 'homes', fieldType: 'text' },
        { key: 'Zip5', label: 'Dwelling Zip', xiloKey: 'zipCode', xiloObject: 'homes', fieldType: 'number' },
    ]},
    { type: 'PriorPolicyInfo', keys: [
      {key: 'PriorCarrier', label: 'Prior Carrier', xiloKey: 'currentCarrier', xiloObject: 'homes', fieldType: 'select'},
      {key: 'Expiration', label: 'Expiration Date', xiloKey: 'coverageExpiration', xiloObject: 'homes', fieldType: 'date'},
      {key: 'YearsWithPriorCarrier.Years', label: 'Years With Prior Carrier', xiloKey: 'yearsWithCompany', xiloObject: 'homes', fieldType: 'select', fieldKey: 'DurationYearsType' },
      {key: 'YearsWithPriorCarrier.Months', label: 'Months With Prior Carrier', xiloKey: 'monthsWithCompany', xiloObject: 'homes', fieldType: 'select', fieldKey: 'DurationMonthsType' },
      {key: 'YearsWithContinuousCoverage.Years', label: 'Years With Home Coverage', xiloKey: 'yearsWithInsurance', xiloObject: 'homes', fieldType: 'select', fieldKey: 'DurationYearsType' },
      {key: 'YearsWithContinuousCoverage.Months', label: 'Months With Home Coverage', xiloKey: 'monthsWithInsurance', xiloObject: 'homes', fieldType: 'select', fieldKey: 'DurationMonthsType' },
      {key: 'ReasonNoPrior', label: 'Reason No Prior', xiloKey: 'noPriorReason', xiloObject: 'homes', fieldType: 'select' },
      {key: 'PriorPolicyPremium', label: 'Prior Premium', xiloKey: 'priorPolicyPremium', xiloObject: 'homes', fieldType: 'number'}
    ]},
    { type: 'PolicyInfo', keys: [
      {key: 'PolicyTerm', label: 'Policy Term', xiloKey: 'coverageTerm', xiloObject: 'homes', fieldType: 'select' },
      {key: 'PolicyType', label: 'Policy Type', xiloKey: 'policyType', xiloObject: 'homes', fieldType: 'select' },
      {key: 'Package', label: 'Has Package', xiloKey: 'hasPackage', xiloObject: 'client', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'Effective', label: 'Effective Date', xiloKey: 'effectiveDate', xiloObject: 'homes', fieldType: 'date' }
    ]},
    { type: 'RatingInfo', keys: [
      {key: 'PropertyInsCancelledLapsed', label: 'Insurance Cancelled or Lapsed', fieldType: 'select', fieldKey: 'BooleanType'},
      {key: 'YearBuilt', label: 'Year Built', xiloKey: 'yearBuilt', xiloObject: 'homes', fieldType: 'select', options: returnArrayByKey('yearBuilt')},
      {key: 'DwellingUse', label: 'Dwelling Use', xiloKey: 'primaryUse', xiloObject: 'homes', fieldType: 'select', fieldKey: 'UseageType'},
      {key: 'Dwelling', label: 'Dwelling Type (# Families)', xiloKey: 'residenceType', xiloObject: 'homes', fieldType: 'select'},
      {key: 'NumberOfFullTimeDomEmps', label: 'Number Of Full Time Dom Emps', fieldType: 'number' },
      {key: 'DistanceToFireHydrant', label: 'Distance To Fire Hydrant', xiloKey: 'distanceFromFireHydrant', xiloObject: 'homes', fieldType: 'select', fieldKey: 'HydrantDistanceType' },
      {key: 'WithinCityLimits', label: 'Within City Limits', xiloKey: 'isInCity', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'WithinProtectedSuburb', label: 'Within Protected Suburb', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'DistanceToFireStation', label: 'Distance To Fire Station', xiloKey: 'distanceFromFireStation', xiloObject: 'homes', fieldType: 'number'},
      {key: 'WithinFireDistrict', label: 'Within Fire District', xiloKey: 'isInFireDistrict', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType'},
      {key: 'ProtectionClass', label: 'Protection Class', xiloKey: 'protectionClass', xiloObject: 'homes', fieldType: 'select' },
      {key: 'NumberOfStories', label: 'Number Of Stories', xiloKey: 'numOfStories', xiloObject: 'homes', fieldType: 'select' },
      {key: 'Construction', label: 'Construction Type', xiloKey: 'exteriorMaterials', xiloObject: 'homes', fieldType: 'select' },
      {key: 'Structure', label: 'Structure Type', xiloKey: 'structureType', xiloObject: 'homes', fieldType: 'select' },
      {key: 'Roof', label: 'Roof Type', xiloKey: 'roofType', xiloObject: 'homes', fieldType: 'select' },
      {key: 'RoofULClass', label: 'Roof UL Class', fieldType: 'select' },
      {key: 'DistanceToBrush', label: 'Distance To Brush', fieldType: 'select' },
      {key: 'DistanceToTidalWater', xiloKey: 'distanceFromTidalWater', xiloObject: 'homes', label: 'Distance To Tidal Water', fieldType: 'select' },
      {key: 'SwimmingPool', label: 'Has Swimming Pool', xiloKey: 'hasPool', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'SwimmingPoolFenced', label: 'Swimming Pool Fenced', xiloKey: 'poolHasFence', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'SwimmingPoolType', label: 'Swimming Pool Type', xiloKey: 'poolType', xiloObject: 'homes', fieldType: 'select' },
      {key: 'DogOnPremises', label: 'Dog On Premises', xiloKey: 'hasDogs', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'HeatingType', label: 'Heating Type', xiloKey: 'heatType', xiloObject: 'homes', fieldType: 'select', fieldKey: 'HomeHeatingType' },
      {key: 'WoodBurningStove', label: 'Wood Burning Stove', xiloKey: 'hasWoodBurningStove', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'NumberOfWoodBurningStoves', label: 'Number of Wood Burning Stoves', xiloKey: 'numberOfWoodBurningStoves', xiloObject: 'homes', fieldType: 'select', options: returnArrayByKey('numberOfWoodBurningStoves') },
      {key: 'RoofingUpdate', label: 'Roofing Update', xiloKey: 'roofUpdateType', xiloObject: 'homes', fieldType: 'select', fieldKey: 'HomeSystemUpdateType' },
      {key: 'RoofingUpdateYear', label: 'Roofing Update Year', xiloKey: 'roofUpdateYear', xiloObject: 'homes', fieldType: 'select', options: returnArrayByKey('roofUpdateYear') },
      {key: 'ElectricalUpdate', label: 'Electrical Update', xiloKey: 'electricalUpdateType', xiloObject: 'homes', fieldType: 'select', fieldKey: 'HomeSystemUpdateType' },
      {key: 'ElectricalUpdateYear', label: 'Electrical Update Year', xiloKey: 'electricalUpdateYear', xiloObject: 'homes', fieldType: 'select', options: returnArrayByKey('electricalUpdateYear') },
      {key: 'PlumbingUpdate', label: 'Plumbing Update', xiloKey: 'key', xiloObject: 'homes', fieldType: 'select', fieldKey: 'HomeSystemUpdateType' },
      {key: 'PlumbingUpdateYear', label: 'Plumbing Update Year', xiloKey: 'plumbingUpdateYear', xiloObject: 'homes', fieldType: 'select', options: returnArrayByKey('plumbingUpdateYear') },
      {key: 'HeatingUpdate', label: 'Heating Update', xiloKey: 'key', xiloObject: 'homes', fieldType: 'select', fieldKey: 'HomeSystemUpdateType' },
      {key: 'HeatingUpdateYear', label: 'Heating Update Year', xiloKey: 'heatingUpdateYear', xiloObject: 'homes', fieldType: 'select', options: returnArrayByKey('heatingUpdateYear') },
      {key: 'ElectricCircuitBreaker', label: 'Electric Circuit Breaker', xiloKey: 'hasCircuitBreakers', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'UnderConstruction', label: 'Under Construction', xiloKey: 'homeUnderConstruction', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'SquareFootage', label: 'Square Footage', xiloKey: 'totalSquareFootage', xiloObject: 'homes', fieldType: 'number' },
      {key: 'NumberOfApartments', label: 'Number Of Apartments', xiloKey: 'numberOfUnits', xiloObject: 'homes', fieldType: 'number' },
      {key: 'PurchaseDate', label: 'Purchase Date', xiloKey: 'purchaseDate', xiloObject: 'homes', fieldType: 'date'},
      {key: 'PurchasePrice', label: 'Purchase Price', xiloKey: 'PurchasePrice', xiloObject: 'homes', fieldType: 'number'},
      {key: 'Trampoline', label: 'Has Trampoline', xiloKey: 'hasTrampolines', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'SecondaryHeatingSource', label: 'Secondary Heating Source', xiloKey: 'hasSecondaryHeatSource', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'SecondaryHeatingSourceType', label: 'Secondary Heating Source Type', xiloKey: 'otherHeatType', xiloObject: 'homes', fieldType: 'select' },
      {key: 'BusinessOnPremises', label: 'Business On Premises', xiloKey: 'hasBusiness', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'FirstMortgagee', label: 'First Mortgagee', xiloKey: 'hasMortgagee', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'SecondMortgagee', label: 'Second Mortgagee', xiloKey: 'hasSecondMortgagee', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'ThirdMortgagee', label: 'Third Mortgagee', xiloKey: 'hasThirdMortgagee', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'EquityLineOfCredit', label: 'Equity Line Of Credit', xiloKey: 'hasLineOfCredit', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'CoSigner', label: 'Co-signer', xiloKey: 'hasCoSigner', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'NumberOfOtherInterests', label: 'Number Of Other Interests', xiloKey: 'numberOfInterests', xiloObject: 'homes', fieldType: 'number' },
      {key: 'RoofShape', label: 'Roof Shape', xiloKey: 'roofShape', xiloObject: 'homes', fieldType: 'select' },
      {key: 'WindSpeed', label: 'Wind Speed', xiloKey: 'windSpeed', xiloObject: 'homes', fieldType: 'select' },
      {key: 'Foundation', label: 'Foundation', fieldType: 'select' },
      {key: 'ReplacementCostExtended.ShapeOfDwelling', xiloKey: 'shapeOfDwelling', xiloObject: 'homes', label: 'Shape Of Dwelling', fieldType: 'select' },
      {key: 'ReplacementCostExtended.ConstructionMethod', label: 'Construction Method', xiloKey: 'constructionMethod', xiloObject: 'homes', fieldType: 'select' },
      {key: 'ReplacementCostExtended.Foundations.Slab', label: 'Percent Foundation is Slab', xiloKey: 'homeFoundationType', xiloObject: 'homes', fieldType: 'select', options: returnArrayByKey('homeFoundationType') },
      {key: 'ReplacementCostExtended.Foundations.CrawlSpace', label: 'Percent Foundation is Crawl Space', xiloKey: 'homeFoundationType', xiloObject: 'homes', fieldType: 'select', options: returnArrayByKey('homeFoundationType') },
      {key: 'ReplacementCostExtended.Foundations.Basement', label: 'Percent Foundation is Basement', xiloKey: 'homeFoundationType', xiloObject: 'homes', fieldType: 'select', options: returnArrayByKey('homeFoundationType') },
      {key: 'ReplacementCostExtended.Foundations.PiersOrPile', label: 'Percent Foundation is Piers Or Pile', xiloKey: 'homeFoundationType', xiloObject: 'homes', fieldType: 'select', options: returnArrayByKey('homeFoundationType') },
      {key: 'ReplacementCostExtended.Foundations.SuspendedOverHillside', label: 'Percent Foundation is Suspended Over Hillside', xiloKey: 'homeFoundationType', xiloObject: 'homes', fieldType: 'select', options: returnArrayByKey('homeFoundationType') },
      {key: 'ReplacementCostExtended.Foundations.BasementInformation.BasementType', label: 'Basement Type', xiloKey: 'basementType', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BasementTypeInfo' },
      {key: 'ReplacementCostExtended.Foundations.BasementInformation.BasementFinished', label: 'Basement Finish Percent', xiloKey: 'basementFinishPercentage', xiloObject: 'homes', fieldType: 'select', options: returnArrayByKey('basementFinishPercentage') },
      {key: 'ReplacementCostExtended.Foundations.BasementInformation.BasementFinishedType', label: 'Basement Finish Type', xiloKey: 'basementFinishType', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BasementFinishedTypeInfo' },
      {key: 'ReplacementCostExtended.LandUnderFoundation', label: 'Land Under Foundation', xiloKey: 'landFoundationType', xiloObject: 'homes', fieldType: 'select' },
      {key: 'ReplacementCostExtended.Kitchens', label: 'Kitchen Type', fieldType: 'select' },
      {key: 'ReplacementCostExtended.HeatingAndCooling.AirConditioning', label: 'Air Conditioning Type', xiloKey: 'coolType', xiloObject: 'homes', fieldType: 'select' },
      {key: 'ReplacementCostExtended.HeatingAndCooling.FirePlace.FirePlace', label: 'Fire Place Type', xiloKey: 'fireplaceType', xiloObject: 'homes', fieldType: 'select', fieldKey: 'FirePlaceTypeType' },
      {key: 'ReplacementCostExtended.HeatingAndCooling.FirePlace.NumberOfFirePlaces', label: 'Number of Fireplaces', xiloKey: 'numberOfFireplaces', xiloObject: 'homes', fieldType: 'select', options: returnArrayByKey('numberOfFireplaces') },
      {key: 'ReplacementCostExtended.GaragesAndCarports.GaragesAndCarports', label: 'Garage Type', xiloKey: 'garageType', xiloObject: 'homes', fieldType: 'select', fieldKey: 'GaragesAndCarportsTypeInfo'},
      {key: 'ReplacementCostExtended.GaragesAndCarports.NumberOfCars', label: 'Garage Size By Number Cars', xiloKey: 'garageSize', xiloObject: 'homes', fieldType: 'select', options: returnArrayByKey('garageSize')},
      {key: 'ReplacementCostExtended.RoofPitch', label: 'Roof Pitch', fieldType: 'select'},
      {key: 'ReplacementCostExtended.Baths.FullBaths.Basic', label: 'Number of Basic Full Baths', xiloKey: 'numOfFullBaths', xiloObject: 'homes', fieldType: 'select', options: returnArrayByKey('numOfFullBaths') },
      {key: 'ReplacementCostExtended.Baths.FullBaths.BuildersGrade', label: 'Number of Builders Grade Full Baths', xiloKey: 'numOfFullBaths', xiloObject: 'homes', fieldType: 'select', options: returnArrayByKey('numOfFullBaths') },
      {key: 'ReplacementCostExtended.Baths.FullBaths.SemiCustom', label: 'Number of Semi Custom Full Baths', xiloKey: 'numOfFullBaths', xiloObject: 'homes', fieldType: 'select', options: returnArrayByKey('numOfFullBaths') },
      {key: 'ReplacementCostExtended.Baths.FullBaths.Custom', label: 'Number of Custom Full Baths', xiloKey: 'numOfFullBaths', xiloObject: 'homes', fieldType: 'select', options: returnArrayByKey('numOfFullBaths') },
      {key: 'ReplacementCostExtended.Baths.FullBaths.Designer', label: 'Number of Designer Full Baths', xiloKey: 'numOfFullBaths', xiloObject: 'homes', fieldType: 'select', options: returnArrayByKey('numOfFullBaths') },
      {key: 'ReplacementCostExtended.Baths.HalfBaths.Basic', label: 'Number of Basic Half Baths', xiloKey: 'numOfHalfBaths', xiloObject: 'homes', fieldType: 'select', options: returnArrayByKey('numOfFullBaths') },
      {key: 'ReplacementCostExtended.Baths.HalfBaths.BuildersGrade', label: 'Number of Builders Grade Half Baths', xiloKey: 'numOfHalfBaths', xiloObject: 'homes', fieldType: 'select', options: returnArrayByKey('numOfFullBaths') },
      {key: 'ReplacementCostExtended.Baths.HalfBaths.SemiCustom', label: 'Number of Semi Custom Half Baths', xiloKey: 'numOfHalfBaths', xiloObject: 'homes', fieldType: 'select', options: returnArrayByKey('numOfFullBaths') },
      {key: 'ReplacementCostExtended.Baths.HalfBaths.Custom', label: 'Number of Custom Half Baths', xiloKey: 'numOfHalfBaths', xiloObject: 'homes', fieldType: 'select', options: returnArrayByKey('numOfFullBaths') },
      {key: 'ReplacementCostExtended.Baths.HalfBaths.Designer', label: 'Number of Designer Half Baths', xiloKey: 'numOfHalfBaths', xiloObject: 'homes', fieldType: 'select', options: returnArrayByKey('numOfFullBaths') },
      {key: 'ReplacementCostExtended.Baths.ThreeQuarterBaths.Basic', label: 'Number of Basic 3/4 Baths', fieldType: 'select', options: returnArrayByKey('numOfFullBaths') },
      {key: 'ReplacementCostExtended.Baths.ThreeQuarterBaths.BuildersGrade', label: 'Number of Builders Grade 3/4 Baths', fieldType: 'select', options: returnArrayByKey('numOfFullBaths') },
      {key: 'ReplacementCostExtended.Baths.ThreeQuarterBaths.SemiCustom', label: 'Number of Semi Custom 3/4 Baths', fieldType: 'select', options: returnArrayByKey('numOfFullBaths') },
      {key: 'ReplacementCostExtended.Baths.ThreeQuarterBaths.Custom', label: 'Number of Custom 3/4 Baths', fieldType: 'select', options: returnArrayByKey('numOfFullBaths') },
      {key: 'ReplacementCostExtended.Baths.ThreeQuarterBaths.Designer', label: 'Number of Designer 3/4 Baths', fieldType: 'select', options: returnArrayByKey('numOfFullBaths') },
    ]},
    { type: 'ReplacementCost', keys: [
      {key: 'ReplacementCost', label: 'Estimated Replacement Cost', xiloKey: 'estimatedReplacementCost', xiloObject: 'homes', fieldType: 'number' },
      {key: 'Dwelling', label: 'Dwelling Coverage', xiloKey: 'dwellingCoverage', xiloObject: 'homes', fieldType: 'number' },
      {key: 'OtherStructures', label: 'Other Structures Coverage', fieldType: 'number' },
      {key: 'LossOfUse', label: 'Loss of Use', xiloKey: 'lossOfUseCoverage', xiloObject: 'homes', fieldType: 'number' },
      {key: 'PersonalProperty', label: 'Personal Property', xiloKey: 'personalPropertyCoverage', xiloObject: 'homes', fieldType: 'number' },
      {key: 'PersonalLiability', label: 'Personal Liability', fieldType: 'select' },
      {key: 'MedicalPayments', label: 'Medical Payments', xiloKey: 'medicalPaymentsCoverage', xiloObject: 'homes', fieldType: 'select' },
      {key: 'NumberOfFamilies', label: 'Number of Families Coverage', fieldType: 'number' },
      {key: 'DeductibeInfo.Deductible', label: 'All Perils Dedctible', xiloKey: 'allPerilsDeductible', xiloObject: 'homes', fieldType: 'select' },
      {key: 'DeductibeInfo.TheftDeductible', label: 'Theft Deductible', xiloKey: 'theftDeductible', xiloObject: 'homes', fieldType: 'select' },
      {key: 'DeductibeInfo.WindDeductible', label: 'Wind Deductible', xiloKey: 'windDeductible', xiloObject: 'homes', fieldType: 'select' },
      {key: 'DeductibeInfo.HurricaneDeductible', label: 'Hurricane Deductible', fieldType: 'select' },
      {key: 'RatingCredits.RetireesCredit', label: 'Retirees Credit', xiloKey: 'retireeDiscount', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'RatingCredits.MatureDiscount', label: 'Mature Discount', xiloKey: 'matureDiscount', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'RatingCredits.RetirementCommunity', label: 'Retirement Community', xiloKey: 'retirementCommunityDiscount', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'RatingCredits.LimitedAccessCommunity', label: 'LimitedAccess Community', xiloKey: 'limitedAccessDiscount', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'RatingCredits.GatedCommunity', label: 'Gated Community', xiloKey: 'gatedCommunityDiscount', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'RatingCredits.NonSmoker', label: 'Non Smoker', xiloKey: 'nonSmokerDiscount', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'RatingCredits.Multipolicy', label: 'Multipolicy', xiloKey: 'hasMultiPolicyDiscount', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
    ]},
    { type: 'Endorsements', keys: [
      {key: 'BuildingAddAlt', label: 'Building Add Alt', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'BuildingAddAltAmount', label: 'Building Add Alt Amount', fieldType: 'number' },
      // {key: 'BusinessPursuits', label: 'Business Pursuits', fieldType: 'select' },
    //   {key: 'CreditCardLimit', label: 'Credit Card Limit', xiloKey: 'key', xiloObject: 'homes', fieldType: 'select' },
      {key: 'IdentityTheft.IdentityTheft', label: 'Identity Theft', xiloKey: 'identityTheft', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'LossAssessment.LossAssessment', label: 'Loss Assessment', xiloKey: 'wantsLossAssessment', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'LossAssessment.Amount', label: 'Loss Assessment Amount', xiloKey: 'lossAssessment', xiloObject: 'homes', fieldType: 'select', fieldKey: 'LossAssessmentAmountType' },
      {key: 'OrdinanceOrLaw.OrdinanceOrLaw', label: 'Ordinance Or Law', xiloKey: 'wantsOrdinanceOrLawIncrease', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'OrdinanceOrLaw.Percent', label: 'Ordinance Or Law Percent', xiloKey: 'ordinanceOrLaw', xiloObject: 'homes', fieldType: 'select', fieldKey: 'OrdinanceOrLawPercentIncreaseType' },
      {key: 'ProtectiveDevices.SmokeDetector.BaseProtectionDevice', label: 'Smoke Detector Type', xiloKey: 'smokeDetectorType', xiloObject: 'homes', fieldType: 'select' },
      {key: 'ProtectiveDevices.SmokeDetector.FireExtinguisher', label: 'Has Fire Extinguisher', xiloKey: 'hasFireExtinguisher', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'ProtectiveDevices.Fire', label: 'Fire System Type', xiloKey: 'fireSystemType', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BaseProtectionDeviceType' },
      {key: 'ProtectiveDevices.TemperatureControl', label: 'Temperature Control Type', xiloKey: 'temparatureControlDeviceType', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BaseProtectionDeviceType' },
      {key: 'ProtectiveDevices.BurglarAlarm.BaseProtectionDevice', label: 'Burglar Alarm Type', xiloKey: 'burglarAlarmType', xiloObject: 'homes', fieldType: 'select' },
      {key: 'ProtectiveDevices.BurglarAlarm.DeadBolt', label: 'Has Deadbolt', xiloKey: 'hasDeadBoltDiscount', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'ProtectiveDevices.BurglarAlarm.VisibleToNeighbor', label: 'Is Visible to Neighbor', xiloKey: 'hasVisibleToNeighborDiscount', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'ProtectiveDevices.BurglarAlarm.MannedSecurity', label: 'Has Manned Security', xiloKey: 'hasMannedSecurityDiscount', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'ProtectiveDevices.Sprinkler', label: 'Sprinkler Type', xiloKey: 'sprinklerSystemType', xiloObject: 'homes', fieldType: 'select' },
      {key: 'PersonalInjury.PersonalInjury', label: 'Wants Personal Injury', xiloKey: 'personalInjuryEndorsement', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'ScheduledPersonalProperty.ScheduledPersonalProperty', label: 'Has Scheduled Personal Property', xiloKey: 'hasAdditionalHighendItems', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'ScheduledPersonalProperty.Coins.Amount', label: 'Amount in Coins', xiloKey: 'coins', xiloObject: 'homes', fieldType: 'number' },
      {key: 'ScheduledPersonalProperty.Coins.Breakage', label: 'Coins Breakage', xiloKey: 'coinsHasBreakage', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'ScheduledPersonalProperty.Furs.Amount', label: 'Amount in Furs', xiloKey: 'fursAmount', xiloObject: 'homes', fieldType: 'number' },
      {key: 'ScheduledPersonalProperty.Furs.Breakage', label: 'Furs Breakage', xiloKey: 'fursHasBreakage', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'ScheduledPersonalProperty.FineArts.Amount', label: 'Amount in Fine Arts', xiloKey: 'fineArtsAmount', xiloObject: 'homes', fieldType: 'number' },
      {key: 'ScheduledPersonalProperty.FineArts.Breakage', label: 'Fine Arts Breakage', xiloKey: 'fineArtsHasBreakage', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'ScheduledPersonalProperty.Guns.Amount', label: 'Amount in Guns', xiloKey: 'gunsAmount', xiloObject: 'homes', fieldType: 'number' },
      {key: 'ScheduledPersonalProperty.Guns.Breakage', label: 'Guns Breakage', xiloKey: 'gunsHasBreakage', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'ScheduledPersonalProperty.Jewelry.Amount', label: 'Amount in Jewelry', xiloKey: 'jewleryAmount', xiloObject: 'homes', fieldType: 'number' },
      {key: 'ScheduledPersonalProperty.Jewelry.Breakage', label: 'Jewelry Breakage', xiloKey: 'jewleryHasBreakage', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'ScheduledPersonalProperty.Music.Amount', label: 'Amount in Music', xiloKey: 'musicAmount', xiloObject: 'homes', fieldType: 'number' },
      {key: 'ScheduledPersonalProperty.Music.Breakage', label: 'Music Breakage', xiloKey: 'musicHasBreakage', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'ScheduledPersonalProperty.Silverware.Amount', label: 'Amount in Silverware', xiloKey: 'silverwareAmount', xiloObject: 'homes', fieldType: 'number' },
      {key: 'ScheduledPersonalProperty.Silverware.Breakage', label: 'Silverware Breakage', xiloKey: 'silverwareHasBreakage', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'ReplacementCostDwelling.ReplacementCostDwelling', label: 'Wants Replacement Cost Dwelling', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'ReplacementCostDwelling.Amount', label: 'Replacement Cost Dwelling Amount', fieldType: 'number' },
      {key: 'ReplacementCostDwelling.ReplacementCostDwellingPercentage', label: 'Replacement Cost Dwelling Percentage', xiloKey: 'increaseReplacementCostPercent', xiloObject: 'homes', fieldType: 'select' },
      {key: 'ReplacementCostContent.ReplacementCostContent', label: 'Wants Replacement Cost Content', xiloKey: 'replacementCostContent', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'ReplacementCostContent.Amount', label: 'Replacement Cost Content Amount', fieldType: 'number' },
      {key: 'IncreasedJewelryWatchesFurs.JewelryWatchesFurs', label: 'Increase Coverage Jewelry Watches Furs', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'IncreasedJewelryWatchesFurs.Amount', label: 'Increased Jewelry Watches Furs Amount', fieldType: 'select', fieldKey: 'JewelryWatchesFursAmountType' },
      {key: 'WaterBackup.WaterBackup', label: 'Wants Water Backup', xiloKey: 'hasWaterBackupCoverage', xiloObject: 'homes', fieldType: 'select', fieldKey: 'BooleanType' },
      {key: 'WaterBackup.Amount', label: 'Water Backup Amount', xiloKey: 'waterBackupCoverage', xiloObject: 'homes', fieldType: 'select' },
    ]},
    { type: 'LossInfo', keys: [
      {key: 'DateOfIncident', label: 'Date', xiloKey: 'date', xiloObject: 'incidents', fieldType: 'date' },
      {key: 'Description', label: 'Description', xiloKey: 'description', xiloObject: 'incidents', fieldType: 'select', fieldKey: 'LossDescriptionType' },
      {key: 'Amount', label: 'Amount', xiloKey: 'amount', xiloObject: 'incidents', fieldType: 'number' },
      {key: 'CATLoss', label: 'CAT Loss', xiloKey: 'catLoss', xiloObject: 'incidents', fieldType: 'select', fieldKey: 'BooleanType' },
    ]},
    { type: 'GeneralInfo', keys: [
      {key: 'RatingStateCode', label: 'Rating State' },
      {key: 'Comments', label: 'Comments', xiloKey: 'comments', xiloObject: 'client', fieldType: 'textarea' }
    ]},
]