import { Company } from './company.model';
import { Question } from './question.model';
import { Parameter } from './parameter.model';
import { Rate } from './rate.model';
import { Condition } from './condition.model';
import { Validation } from './validation.model';
import { Integration } from './integration.model';
import { OptionGroup } from './option-group.model';

export class Answer {
    constructor(
      public id?: string,
      public isInput?: boolean,
      public isSelect?: boolean,
      public isNativeSelect?: boolean,
      public isDatePicker?: boolean,
      public isMobileDatePicker?: boolean,
      public isButton?: boolean,
      public isTextarea?: boolean,
      public isAutocomplete?: boolean,
      public isProgressButton?: boolean,
      public isRequired?: boolean,
      public hasSuffix?: boolean,
      public hasPrefix?: boolean,
      public suffixText?: string,
      public prefixText?: string,
      public placeholderText?: string,
      public hasSecondaryPlaceholder?: boolean,
      public secondaryPlaceholderText?: string,
      public propertyValue?: string,
      public propertyKey?: string,
      public displayValue?: string,
      public startDate?: string,
      public width?: string,
      public position?: number,
      public hasCustomHtml?: boolean,
      public isPrevNextButtons?: boolean,
      public customAnswerHtml?: string,
      public fireNewLead?: boolean,
      public isVehicleVIN?: boolean,
      public isVehicleYear?: boolean,
      public isVehicleMakeModel?: boolean,
      public isAddressSearch?: boolean,
      public isAddVehicle?: boolean,
      public isAddDriver?: boolean,
      public hasInformationIcon?: boolean,
      public informationIconText?: string,
      public errorText?: string,
      public isConditional?: boolean,
      public isConditionParent?: boolean,
      public conditionValue?: string,
      public conditionKey?: string,
      public options?: string[],
      public isAgeInput?: boolean,
      public isViolationTracker?: boolean,
      public isCheckbox?: boolean,
      public usDotKey?: string,
      public hawksoftKey?: string,
      public ezlynxKey?: string,
      public conditionAnswerId?: number,
      public questionAnswerId?: number,
      public formAnswerId?: number,
      public companyAnswerId?: number,
      public company?: Company,
      public parameters?: Parameter[],
      public rates?: Rate[],
      public dateStartView?: string,
      public hasFilter?: boolean,
      public isSquareFootage?: boolean,
      public isHomeFinishings?: boolean,
      public isFirstName?: boolean,
      public isLastName?: boolean,
      public isEmail?: boolean,
      public isPhone?: boolean,
      public isSpacer?: boolean,
      public isText?: boolean,
      public isVehicleMake?: boolean,
      public isVehicleModel?: boolean,
      public isVehicleBodyStyle?: boolean,
      public defaultValue?: string,
      public filterCondition?: string,
      public isLink?: boolean,
      public externalLink?: string,
      public objectName?: string,
      public getUSDotData?: boolean,
      public getHomeData?: boolean,
      public pageAnswerId?: number,
      public getRate?: boolean,
      public style?: string,
      public isMultipleSelect?: boolean,
      public question?: Question,
      public isSecureDocumentUpload?: boolean,
      public isHiddenInput?: boolean,
      public isAddLocation?: boolean,
      public isAddHome?: boolean,
      public isAddInsuranceCoverages?: boolean,
      public isTemplate?: boolean,
      public templateCategory?: string,
      public templateTitle?: string,
      public isCard?: boolean,
      public headerText?: string,
      public icon?: string,
      public transformResponse?: string,
      public validationType?: string,
      public columns?: string[],
      public filters?: string[],
      public isAddIncident?: boolean,
      public isAddRecreationalVehicle?: boolean,
      public isAddPolicy?: boolean,
      public isSelectObject?: boolean,
      public selectObjectName?: string,
      public answerConditions?: Condition[],
      public isLoginWithFacebook?: boolean,
      public isLoginWithGoogle?: boolean,
      public isOccupation?: boolean,
      public isIndustry?: boolean,
      public panelIsOpen?: boolean,
      public isEZValid?: boolean,
      public isScale?: boolean,
      public hasEducationalDropdown?: boolean,
      public validations?: Validation[],
      public integrations?: Integration[],
      public hasLabeledSelectOptions?: boolean,
      public labeledSelectOptions?: OptionGroup[],
      public isURL?: boolean,
    ) {}
}
