import { Carrier } from './carrier.model';
import { Client } from './client.model';
import { Agent } from './agent.model';
import { Lifecycle } from './lifecycle.model';
import { User } from './user.model';
import { PlatformManager } from './platform-manager.model';
import { LifecycleAnalytic } from './lifecycle-analytic.model';
import { Note } from './note.model';
import { LandingPage } from './landing-page.model';
import { CTA } from './cta.model';
import { Medium } from './medium.model';
import { Form } from './form.model';
import { Discount } from './discount.model';
import { Home } from './home.model';
import { Vehicle } from './vehicle.model';
import { Driver } from './driver.model';
import { PaymentDetails } from './payment.model';

export class Company {
  constructor(
    public id?: number,
    public name?: string,
    public slogan?: string,
    public contactNumber?: string,
    public contactEmail?: string,
    public mainLocation?: string,
    public logo?: string,
    public customerId?: string,
    public cardId?: string,
    public cardLast4?: string,
    public subscriptionId?: string,
    public addedPayment?: Boolean,
    public hasActiveSubscription?: Boolean,
    public companyId?: string,
    public companyWebsite?: string,
    public navbarBackgroundColorStart?: string,
    public navbarBackgroundColorEnd?: string,
    public navbarFontColor?: string,
    public emailText?: string,
    public navbarFont?: string,
    public resetPasswordLink?: string,
    public rqUid?: string,
    public facebookApiKey?: string,
    public klaviyoApiKey?: string,
    public redirectCompany?: Boolean,
    public redirectUrl?: string,
    public brandColor?: string,
    public accentColor?: string,
    public hasApplied?: boolean,
    public hasAppliedEpic?: boolean,
    public hasEzlynx?: boolean,
    public pipedriveIntegration?: boolean,
    public pipedriveToken?: string,
    public pipedriveUrl?: string,
    public pipedriveStage?: string,
    public pipedriveStageId?: string,
    public pipedrivePipeline?: string,
    public pipedrivePipelineId?: string,
    public hasEstimations?: boolean,
    public fireFirstEmailAuto?: boolean,
    public fireSecondEmailAuto?: boolean,
    public hasGoogleConversions?: boolean,
    public googleAdwordsCustomerId?: string,
    public googleAnalyticsViewId?: string,
    public googleApiAccessToken?: string,
    public googleApiRefreshToken?: string,
    public logoHeight?: string,
    public hasSalesforce?: boolean,
    public salesforceU?: string,
    public salesforceP?: string,
    public accessToken?: string,
    public hasFollowUpEmail?: boolean,
    public headerText?: string,
    public subHeaderText?: string,
    public placeholderText?: string,
    public secondaryPlaceholderText?: string,
    public buttonText?: string,
    public textNumber?: string,
    public ezlynxRqUid?: string,
    public hasEzlynxIntegration?: boolean,
    public listClientDetailsOnEmail?: boolean,
    public updatedAt?: Date,
    public createdAt?: Date,
    public platformManagerCompanyId?: number,
    public hasSalesAutomation?: boolean,
    public mainProducer?: string,
    public producerNumber?: string,
    public tags?: string[],
    public agents?: Agent[],
    public carriers?: Carrier[],
    public clients?: Client[],
    public ctas?: CTA[],
    public landingPages?: LandingPage[],
    public lifecycles?: Lifecycle[],
    public lifecycleAnalytics?: LifecycleAnalytic[],
    public mediums?: Medium[],
    public notes?: Note[],
    public discounts?: Discount[],
    public users?: User[],
    public forms?: Form[],
    public hubspotApiKey?: string,
    public hubspotIntegration?: boolean,
    public hasUSDotIntegration?: boolean,
    public hasHawksoftIntegration?: boolean,
    public hasQQIntegration?: boolean,
    public addedEzlynxDefaults?: boolean,
    public addedHawksoftDefaults?: boolean,
    public ezlynxIntegrationId?: number,
    public salesforceIntegrationId?: number,
    public hawksoftIntegrationId?: number,
    public qqIntegrationId?: number,
    public hasInfusionsoftIntegration?: boolean,
    public infusionsoftApiAccessToken?: string,
    public infusionsoftApiRefreshToken?: string,
    public hasTags?: boolean,
    public hasNotes?: boolean,
    public drivers?: Driver[],
    public homes?: Home[],
    public vehicle?: Vehicle[],
    public platformManager?: PlatformManager,
    public hasTurboraterIntegration?: boolean,
    public turboraterIntegrationId?: number,
    public hasGoogleEvents?: boolean,
    public googleAnalyticsId?: string,
    public hasQuoteRushIntegration?: boolean,
    public quoteRushIntegrationId?: number,
    public hasAgencyMatrixIntegration?: boolean,
    public hasCabrilloIntegration?: boolean,
    public cabrilloIntegrationId?: number,
    public hasCarrierIntegrations?: boolean,
    public hasNowCertsIntegration?: boolean,
    public hasAppulateIntegration?: boolean,
    public hasAgencySoftwareIntegration?: boolean,
    public hasAMS360Integration?: boolean,
    public hasWealthboxIntegration?: boolean,
    public hasMyEvo?: boolean,
    public hasPartnerXE?: boolean,
    public hasRicochet?: boolean,
    public streetNumber?: string,
    public streetName?: string,
    public streetAddress?: string,
    public city?: string,
    public state?: string,
    public zipCode?: string,
    public fullAddress?: string,
    public county?: string,
    public unit?: string,
    public hasCommercialEzlynxIntegration?: boolean,
    public commercialEzlynxIntegrationId ?: number,
    public hasTasks?: boolean,
    public hasGoogleIntegration ?: boolean,
    public hasOutlookIntegration ?: boolean,
    public outlookAccessToken?: string,
    public outlookRefreshToken?: string,
    public hasZapier?: string,
    public hasV2Integrations?: boolean,
    public hasPLRater?: boolean,
    public payment?: PaymentDetails,
    public preselectedIntegrations?: Array<any>,
    public brandSecondaryColor?: string,
    public hasBetterAgency?: boolean,
    public features?: object,
    public integrations?: object,
    public showLeadSourceOnTable?: boolean,
    public brandingURL?: string,
  ) {}
}
