import { Driver } from "./driver.model";
import { Rate } from "./rate.model";

export class Vehicle {
  constructor(
    public id?: string,
    public applicantAddrCd?: string,
    public applicantAddrStreetName?: string,
    public applicantAddrStreetNumber?: string,
    public applicantUnitNumber?: string,
    public applicantAddrCity?: string,
    public applicantStateCd?: string,
    public applicantPostalCd?: string,
    public vehicleManufacturer?: string,
    public vehicleManufacturerId?: string,
    public vehicleModel?: string,
    public vehicleBodyStyle?: string,
    public vehicleModelId?: string,
    public vehicleModelYear?: number,
    public vehicleDaysDrivenPerWeek?: string,
    public vehicleMilesDrivenPerDay?: string,
    public vehicleCommuteMilesDrivenOneWay?: string,
    public vehicleAnnualDistance?: string,
    public vehicleAnnualDistanceUnitCd?: string,
    public vehicleVin?: string,
    public vehicleUseCd?: string,
    public liveNearCity?: string,
    public driveSportLuxury?: string,
    public isGaragedNearCity?: boolean,
    public isHighPerformanceVehicle?: boolean,
    public ownOrLeaseVehicle?: string,
    public vehicleScore?: number,
    public coverageLevel?: string,
    public premiumTotal?: number,
    public premiumMonths?: number,
    public premiumEndDate?: Date,
    public hasRatesCreated?: boolean,
    public weight?: string,
    public value?: string,
    public collision?: string,
    public comprehensive?: string,
    public deductible?: string,
    public radius?: string,
    public sfVehicleId?: string,
    public companyVehicleId?: number,
    public clientVehicleId?: number,
    public driver?: Driver,
    public rates?: Rate[],
    public vehicleId?: number
  ) {}
}