import {
  IsString,
  IsDate,
  IsNumber,
  IsOptional,
  IsObject,
  IsBoolean,
} from 'class-validator';
import { Companies } from '../../company/company.entity';
import { Businesses } from '../../business/businesses.entity';
import { Drivers } from '../../driver/drivers.entity';
import { Homes } from '../../home/homes.entity';
import { Vehicles } from '../../../entities/Vehicles';

export class ClientDto {
  @IsOptional() @IsNumber() id?: number;
  @IsOptional() @IsDate() readonly createdAt?: Date;
  @IsOptional() @IsDate() readonly updatedAt?: Date;
  @IsOptional() @IsNumber() premiumTotal?: number;
  @IsOptional() @IsNumber() premiumMonths?: number;
  @IsOptional() @IsString() pipedriveDealId?: string;
  @IsOptional() @IsString() pipedriveNoteId?: string;
  @IsOptional() @IsString() firstName?: string;
  @IsOptional() @IsString() lastName?: string;
  @IsOptional() @IsString() phone?: string;
  @IsOptional() @IsString() email?: string;
  @IsOptional() @IsString() streetName?: string;
  @IsOptional() @IsString() streetNumber?: string;
  @IsOptional() @IsString() city?: string;
  @IsOptional() @IsString() stateCd?: string;
  @IsOptional() @IsString() postalCd?: string;
  @IsOptional() @IsNumber() companyClientId?: number;
  @IsOptional() @IsBoolean() completedAutoForm?: boolean;
  @IsOptional() @IsNumber() latitude?: number;
  @IsOptional() @IsNumber() longitude?: number;
  @IsOptional() @IsString() gender?: string;
  @IsOptional() birthDate?: Date;
  @IsOptional() @IsString() tag?: string;
  @IsOptional() @IsBoolean() hasCancelled?: boolean;
  @IsOptional() @IsString() educationLevel?: string;
  @IsOptional() @IsBoolean() priorClient?: boolean;
  @IsOptional() @IsString() maritalStatus?: string;
  @IsOptional() @IsString() occupation?: string;
  @IsOptional() @IsString() sfAccountId?: string;
  @IsOptional() @IsString() sfContactId?: string;
  @IsOptional() @IsString() sfInsuranceId?: string;
  @IsOptional() @IsNumber() sequenceNumber?: number;
  @IsOptional() @IsBoolean() hasFollowUpEmail?: boolean;
  @IsOptional() @IsString() numOfLosses?: string;
  @IsOptional() @IsString() creditScore?: string;
  @IsOptional() @IsBoolean() newLeadFired?: boolean;
  @IsOptional() @IsString() lengthAtAddress?: string;
  @IsOptional() @IsString() raterResponseStatus?: string;
  @IsOptional() @IsString() raterResponse?: string;
  @IsOptional() @IsString() qqContactId?: string;
  @IsOptional() @IsString() qqPolicyId?: string;
  @IsOptional() @IsString() ezlynxUrl?: string;
  @IsOptional() @IsString() hasPriorInsurance?: string;
  @IsOptional() @IsString() priorInsuranceCompany?: string;
  @IsOptional() @IsString() priorInsuranceDuration?: string;
  @IsOptional() @IsString() fullAddress?: string;
  @IsOptional() @IsString() priorPenalties?: string;
  @IsOptional() @IsString() priorPenaltiesCode?: string;
  @IsOptional() @IsString() priorPenaltiesDate?: string;
  @IsOptional() @IsString() priorInsuranceYears?: string;
  @IsOptional() @IsString() priorInsuranceMonths?: string;
  @IsOptional() @IsString() yearsWithCarrier?: string;
  @IsOptional() @IsString() monthsWithCarrier?: string;
  @IsOptional() @IsString() priorInsuranceExpirationDate?: string;
  @IsOptional() @IsString() homeownership?: string;
  @IsOptional() @IsString() hasAccidents?: string;
  @IsOptional() @IsString() accidentDate?: string;
  @IsOptional() @IsString() accidentType?: string;
  @IsOptional() @IsString() hasViolations?: string;
  @IsOptional() @IsString() violationDate?: string;
  @IsOptional() @IsString() violationType?: string;
  @IsOptional() @IsString() hasCompLoss?: string;
  @IsOptional() @IsString() compLossDate?: string;
  @IsOptional() @IsString() compLossType?: string;
  @IsOptional() @IsString() isFirstTimeHomeBuyer?: string;
  @IsOptional() @IsString() homeInsurancePreviouslyCancelled?: string;
  @IsOptional() @IsString() hasSecondAddress?: string;
  @IsOptional() @IsString() hasHomeLoss?: string;
  @IsOptional() @IsString() homeLossDate?: string;
  @IsOptional() @IsString() homeLossType?: string;
  @IsOptional() @IsString() homeLossAmount?: string;
  @IsOptional() @IsString() hasUnitNumber?: string;
  @IsOptional() @IsString() priorPolicyPaidInFull?: string;
  @IsOptional() @IsString() priorPolicyPaymentMethod?: string;
  @IsOptional() @IsString() payThroughEscrow?: string;
  @IsOptional() @IsString() numberOfResidentsInHome?: string;
  @IsOptional() @IsString() rentersLimits?: string;
  @IsOptional() @IsString() homeHasMortgage?: string;
  @IsOptional() @IsString() isPriorClient?: string;
  @IsOptional() @IsString() authCreditCheck?: string;
  @IsOptional() @IsString() priorBodilyInjuryLimits?: string;
  @IsOptional() @IsString() preferredContactMethod?: string;
  @IsOptional() @IsString() vehicleCoverageLevel?: string;
  @IsOptional() @IsString() height?: string;
  @IsOptional() @IsString() weight?: string;
  @IsOptional() @IsString() nicotineUse?: string;
  @IsOptional() @IsString() healthRating?: string;
  @IsOptional() @IsString() typeOfInsurance?: string;
  @IsOptional() @IsString() coverageTerm?: string;
  @IsOptional() @IsString() coverageNeeded?: string;
  @IsOptional() @IsString() referredBy?: string;
  @IsOptional() @IsString() preferredAgent?: string;
  @IsOptional() @IsString() permissionToContact?: string;
  @IsOptional() @IsString() marriedOrHasCoBorrower?: string;
  @IsOptional() @IsString() spouseName?: string;
  @IsOptional() @IsString() spouseBirthdate?: string;
  @IsOptional() @IsString() referrersFirstName?: string;
  @IsOptional() @IsString() referrersLastName?: string;
  @IsOptional() @IsString() referrersEmail?: string;
  @IsOptional() @IsString() reasonForShopping?: string;
  @IsOptional() @IsString() referrersPhone?: string;
  @IsOptional() tags?: string[];
  @IsOptional() @IsString() wantsLiabilityCoverage?: string;
  @IsOptional() @IsString() timeToQuote?: string;
  @IsOptional() @IsString() hasOtherLicensedDrivers?: string;
  @IsOptional() @IsString() hadLoss?: string;
  @IsOptional() @IsString() lossExplanation?: string;
  @IsOptional() @IsString() priorInsurancePremium?: string;
  @IsOptional() @IsString() yearsWithLapseInInsurance?: string;
  @IsOptional() @IsString() monthsWithLapseInInsurance?: string;
  @IsOptional() @IsString() hasMedicare?: string;
  @IsOptional() medications?: string[];
  @IsOptional() @IsString() hasFamilyWithDiseases?: string;
  @IsOptional() @IsString() hadLicenseSuspended?: string;
  @IsOptional() @IsString() isBusinessPartner?: string;
  @IsOptional() @IsString() hadLapseInInsurance?: string;
  @IsOptional() @IsString() wantsCyberLiability?: string;
  @IsOptional() @IsString() priorInsuranceStartDate?: string;
  @IsOptional() @IsString() liabilityLimits?: string;
  @IsOptional() @IsString() hadLiabilityClaims?: string;
  @IsOptional() @IsString() liabilityClaimExplanation?: string;
  @IsOptional() @IsString() reasonForInsuranceExplanation?: string;
  @IsOptional() @IsString() nicotineFrequency?: string;
  @IsOptional() @IsString() infusionsoftClientId?: string;
  @IsOptional() @IsNumber() formClientId?: number;
  @IsOptional() @IsBoolean() finishedFormEmailFired?: boolean;
  @IsOptional() @IsString() entityName?: string;
  @IsOptional() @IsString() effectiveDate?: string;
  @IsOptional() @IsString() policyType?: string;
  @IsOptional() @IsString() goalsWithNewInsurance?: string;
  @IsOptional() @IsString() businessDecisionsDescription?: string;
  @IsOptional() @IsString() hasCompletedQuoteForm?: string;
  @IsOptional() @IsString() hasPreviousAddress?: string;
  @IsOptional() @IsString() previousAddress?: string;
  @IsOptional() @IsString() coverageDescription?: string;
  @IsOptional() @IsString() desiredPremium?: string;
  @IsOptional() @IsString() wantsLifeBundle?: string;
  @IsOptional() @IsString() hasLlc?: string;
  @IsOptional() @IsString() streetAddress?: string;
  @IsOptional() @IsString() fullName?: string;
  @IsOptional() @IsString() isMarried?: string;
  @IsOptional() @IsString() yearsAtCurrentAddress?: string;
  @IsOptional() @IsString() isUsCitizen?: string;
  @IsOptional() @IsString() hasBeneficiaries?: string;
  @IsOptional() @IsString() numberOfBeneficiaries?: string;
  @IsOptional() @IsString() valueOfAssets?: string;
  @IsOptional() @IsString() hasRealEstate?: string;
  @IsOptional() @IsString() numberOfProperties?: string;
  @IsOptional() @IsString() hasVehicles?: string;
  @IsOptional() @IsString() numberOfVehicles?: string;
  @IsOptional() @IsString() hasLifeInsurance?: string;
  @IsOptional() @IsString() typeOfLifeInsurance?: string;
  @IsOptional() @IsString() hasRetirementAccounts?: string;
  @IsOptional() typeOfRetirementAccounts?: string[];
  @IsOptional() @IsString() comments?: string;
  @IsOptional() @IsString() primaryPowerOfAttorney?: string;
  @IsOptional() @IsString() secondaryPowerOfAttorney?: string;
  @IsOptional() @IsString() contingencyPowerOfAttorney?: string;
  @IsOptional() typesOfInsurances?: string[];
  @IsOptional() @IsString() county?: string;
  @IsOptional() @IsString() ssn?: string;
  @IsOptional() @IsString() additionalInsured?: string;
  @IsOptional() @IsString() policyNumber?: string;
  @IsOptional() otherInsurances?: string[];
  @IsOptional() @IsString() spouseOccupation?: string;
  @IsOptional() @IsString() numberOfResidentsUnder14?: string;
  @IsOptional() @IsString() numberOfResidentsOver13?: string;
  @IsOptional() @IsString() membershipDiscounts?: string;
  @IsOptional() @IsString() today?: string;
  @IsOptional() @IsString() expirationDate?: string;
  @IsOptional() @IsString() hasMinorDrivers?: string;
  @IsOptional() @IsString() hasFarms?: string;
  @IsOptional() @IsString() hasWatercrafts?: string;
  @IsOptional() @IsString() hasRecreationalVehicles?: string;
  @IsOptional() @IsString() hasRentals?: string;
  @IsOptional() @IsString() numberOfHomes?: string;
  @IsOptional() clientAgentIdUpdatedAt?: Date;
  @IsOptional() @IsString() clubMembershipsText?: string;
  @IsOptional() @IsString() referralType?: string;
  @IsOptional() @IsString() referralName?: string;
  @IsOptional() @IsString() referralEmail?: string;
  @IsOptional() @IsString() referralPhone?: string;
  @IsOptional() vehicleDiscounts?: string[];
  @IsOptional() homeDiscounts?: string[];
  @IsOptional() @IsString() priorPolicyTerm?: string;
  @IsOptional() @IsString() wantsUmbrellaCoverage?: string;
  @IsOptional() @IsString() wantsHomeBundle?: string;
  @IsOptional() @IsString() beneficiary?: string;
  @IsOptional() @IsString() hasAppliedForInsurance?: string;
  @IsOptional() @IsString() annualIncome?: string;
  @IsOptional() @IsString() networth?: string;
  @IsOptional() @IsString() totalSavings?: string;
  @IsOptional() @IsString() totalExpenses?: string;
  @IsOptional() @IsString() yearsUntilRetirement?: string;
  @IsOptional() @IsString() driversList?: string;
  @IsOptional() @IsString() vehiclesList?: string;
  @IsOptional() @IsString() mailingAddress?: string;
  @IsOptional() @IsString() additionalCommentOne?: string;
  @IsOptional() @IsString() additionalCommentTwo?: string;
  @IsOptional() @IsString() additionalCommentThree?: string;
  @IsOptional() @IsString() additionalCommentFour?: string;
  @IsOptional() @IsString() hasCreditCheckAuthorization?: string;
  @IsOptional() @IsString() spouseFirstName?: string;
  @IsOptional() @IsString() spouseLastName?: string;
  @IsOptional() @IsString() spouseGender?: string;
  @IsOptional() @IsString() spouseMaritalStatus?: string;
  @IsOptional() @IsString() spouseEducationLevel?: string;
  @IsOptional() @IsString() wealthboxId?: string;
  @IsOptional() @IsString() customerType?: string;
  @IsOptional() @IsString() hasMedicalConditions?: string;
  @IsOptional() @IsString() conditionDuration?: string;
  @IsOptional() @IsString() conditionOutcome?: string;
  @IsOptional() @IsString() ssnHash?: string;
  @IsOptional() @IsString() autoCoverageTerm?: string;
  @IsOptional() @IsString() amsCustomerId?: string;
  @IsOptional() @IsString() amsPolicyId?: string;
  @IsOptional() @IsString() ezlynxId?: string;
  @IsOptional() @IsString() umbrellaCoverageAmount?: string;
  @IsOptional() @IsString() consent?: string;
  @IsOptional() @IsString() ownerIsDriver?: string;
  @IsOptional() @IsString() wantsGeneralLiability?: string;
  @IsOptional() @IsString() hasLaneKeepAssistance?: string;
  @IsOptional() @IsString() hasSelfDrivingCar?: string;
  @IsOptional() @IsString() hasLowMileageVehicle?: string;
  @IsOptional() @IsString() hasDrivingMonitor?: string;
  @IsOptional() @IsString() expectedValue?: string;
  @IsOptional() @IsString() hasCancelledPriorPolicy?: string;
  @IsOptional() lifecycleUpdatedAt?: Date;
  @IsOptional() triggeredFormIds?: number[];
  @IsOptional() @IsString() employer?: string;
  @IsOptional() currentInsurancePolicies?: string[];
  @IsOptional() @IsString() wantsRentalReimbursementCoverage?: string;
  @IsOptional() @IsString() isPregnant?: string;
  @IsOptional() @IsString() numberOfDependents?: string;
  @IsOptional() @IsString() hasToys?: string;
  @IsOptional() @IsString() spouseEmployer?: string;
  @IsOptional() @IsString() doctorsVisitReason?: string;
  @IsOptional() @IsString() authorizedHealthRelease?: string;
  @IsOptional() @IsString() hasContingentBeneficiaries?: string;
  @IsOptional() @IsString() contingentBeneficiaries?: string;
  @IsOptional() @IsString() appliedForDisability?: string;
  @IsOptional() @IsString() disabilityDetails?: string;
  @IsOptional() @IsString() insuranceDeclined?: string;
  @IsOptional() @IsString() insuranceDeclineDetails?: string;
  @IsOptional() @IsString() inAviation?: string;
  @IsOptional() @IsString() doesExtremeSports?: string;
  @IsOptional() @IsString() extremeSports?: string;
  @IsOptional() @IsString() inMilitary?: string;
  @IsOptional() @IsString() militaryDetails?: string;
  @IsOptional() @IsString() criminal?: string;
  @IsOptional() @IsString() criminalDetails?: string;
  @IsOptional() @IsString() hasOtherClaims?: string;
  @IsOptional() @IsString() otherClaimDetails?: string;
  @IsOptional() @IsString() receiveAtAddress?: string;
  @IsOptional() @IsString() country?: string;
  @IsOptional() @IsString() billPlan?: string;
  @IsOptional() @IsString() faceAmount?: string;
  @IsOptional() @IsString() hasScheduledProperty?: string;
  @IsOptional() @IsString() hasUmbrellaPolicy?: string;
  @IsOptional() @IsString() naicCode?: string;
  @IsOptional() @IsString() spousePhoneNumber?: string;
  @IsOptional() @IsString() spouseEmail?: string;
  @IsOptional() listOfTimesToContact?: string[];
  @IsOptional() @IsString() insuranceCarrierAddress?: string;
  @IsOptional() @IsString() cancellationDate?: string;
  @IsOptional() @IsString() interestType?: string;
  @IsOptional() @IsString() interestsMailingAddress?: string;
  @IsOptional() @IsString() cancelReason?: string;
  @IsOptional() @IsString() cancelReasonOther?: string;
  @IsOptional() @IsString() newCarrier?: string;
  @IsOptional() @IsString() newPolicyNumber?: string;
  @IsOptional() @IsString() newEffectiveDate?: string;
  @IsOptional() @IsString() cancelMethod?: string;
  @IsOptional() @IsString() premiumFactor?: string;
  @IsOptional() @IsString() returnPremium?: string;
  @IsOptional() @IsString() premiumAudit?: string;
  @IsOptional() @IsString() interestFullName?: string;
  @IsOptional() @IsString() priorEvidenceDate?: string;
  @IsOptional() @IsString() typeOfCoverage?: string;
  @IsOptional() @IsString() insurerLetterCode?: string;
  @IsOptional() @IsString() aggregateCoverage?: string;
  @IsOptional() @IsString() umbrellaPolicyType?: string;
  @IsOptional() @IsString() coverageBasis?: string;
  @IsOptional() @IsString() officerExcludeInclude?: string;
  @IsOptional() @IsString() eachAccidentLimit?: string;
  @IsOptional() @IsString() eachEmpLimit?: string;
  @IsOptional() @IsString() workcompPolicyLimit?: string;
  @IsOptional() @IsString() otherCoverageDescription?: string;
  @IsOptional() @IsString() liabilityLimitsDescription?: string;
  @IsOptional() @IsString() loanNumber?: string;
  @IsOptional() @IsString() authorizedRep?: string;
  @IsOptional() @IsString() attachmentLink?: string;
  @IsOptional() @IsString() infusionsoftTagId?: string;
  @IsOptional() @IsString() approver?: string;
  @IsOptional() @IsString() reinstatementAmount?: string;
  @IsOptional() @IsString() producer?: string;
  @IsOptional() @IsString() monthsAtAddress?: string;
  @IsOptional() @IsString() changeOfResidency?: string;
  @IsOptional() @IsString() witness?: string;
  @IsOptional() @IsString() dateReinstatementFeePaid?: string;
  @IsOptional() @IsString() title?: string;
  @IsOptional() @IsString() agencyName?: string;
  @IsOptional() @IsString() newProducer?: string;
  @IsOptional() @IsString() newAgencyName?: string;
  @IsOptional() @IsString() newProducerCode?: string;
  @IsOptional() @IsString() newAgencyAppointmentDate?: string;
  @IsOptional() @IsString() zapStatus?: string;
  @IsOptional() @IsString() agencyFullAddress?: string;
  @IsOptional() @IsString() agencyStreetAddress?: string;
  @IsOptional() @IsString() agencyStreetName?: string;
  @IsOptional() @IsString() agencyStreetNumber?: string;
  @IsOptional() @IsString() agencyUnitNumber?: string;
  @IsOptional() @IsString() agencyCity?: string;
  @IsOptional() @IsString() agencyState?: string;
  @IsOptional() @IsString() agencyZipCode?: string;
  @IsOptional() ezlynxValidationLogs?: string[];
  @IsOptional() @IsString() informationRelease?: string;
  @IsOptional() @IsString() roommateRelationship?: string;
  @IsOptional() @IsString() changeRequest?: string;
  @IsOptional() @IsString() ezlynxStatus?: string;
  @IsOptional() @IsString() industry?: string;
  @IsOptional() @IsString() spouseIndustry?: string;
  @IsOptional() @IsString() disclose?: string;
  @IsOptional() paymentMethodList?: string[];
  @IsOptional() @IsString() hasSameBiAndUm?: string;
  @IsOptional() @IsString() previousAddressUnit?: string;
  @IsOptional() @IsString() wantsPetInsurance?: string;
  @IsOptional() @IsString() billPlanList?: string;
  @IsOptional() @IsString() preferredContactTime?: string;
  @IsOptional() @IsString() beneficiaryName?: string;
  @IsOptional() @IsString() yearsAtPreviousAddress?: string;
  @IsOptional() @IsString() monthsAtPreviousAddress?: string;
  @IsOptional() @IsString() monthsAtCurrentAddress?: string;
  @IsOptional() @IsString() addressCode?: string;
  @IsOptional() @IsString() spouseSsn?: string;
  @IsOptional() @IsString() spouseSsnHash?: string;
  @IsOptional() @IsString() spouseRelationship?: string;
  @IsOptional() @IsString() hasAdditionalVehiclesNotInsured?: string;
  @IsOptional() isExistingEzLynxApplicant?: boolean;
  @IsOptional() @IsString() relationship?: string;
  @IsOptional() @IsString() yearsSinceHospittalized?: string;
  @IsOptional() @IsObject() validations?: object;
  @IsOptional() integrationsAreValid?: boolean;
  @IsOptional() @IsString() formStatus?: string;
  @IsOptional() cronTriggerFireDate?: Date;
  @IsOptional() cronTriggerLog?: string[];
  @IsOptional() company?: Companies;
  @IsOptional() businesses?: Businesses[];
  @IsOptional() business?: Businesses;
  @IsOptional() clientAgentId?: number;
  @IsOptional() unitNumber?: string | null;
  @IsOptional() drivers?: Drivers[];
  @IsOptional() homes?: Homes[];
  @IsOptional() vehicles?: Vehicles[];
}
